# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WindowsBuild

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download 3rd party
      run: .\Setup.bat

    - name: Build
      run: .\Build.bat
